services:
  - type: web
    name: flow-note
    env: node
    rootDir: flow_note
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
