plugins {
    id 'com.android.application'
}

android {
    namespace 'com.flow.note'
    compileSdk 34

    defaultConfig {
        applicationId "com.flow.note"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

task copyWebAssets(type: Copy) {
    from '../../flow_note/public'
    into 'src/main/assets/web'
}

preBuild.dependsOn copyWebAssets

task copyPdfAssets(type: Copy) {
    from '../../flow_pdf/public'
    into 'src/main/assets/pdf'
}

preBuild.dependsOn copyPdfAssets
